# 作業 : (Kaggle)鐵達尼生存預測精簡版 
https://www.kaggle.com/c/titanic

# 作業1
* 下列A~E五個程式區塊中，哪一塊是特徵工程?
C

# 作業2
* 對照程式區塊 B 與 C 的結果，請問那些欄位屬於"類別型欄位"? (回答欄位英文名稱即可) 
Pclass, Sex, Ticket, Cabin, Embarked

# 作業3
* 續上題，請問哪個欄位是"目標值"?
Survived

In [16]:
# 程式區塊 A
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder, MinMaxScaler

data_path = 'data/'
df_train = pd.read_csv(data_path + 'titanic_train.csv')
df_test = pd.read_csv(data_path + 'titanic_test.csv')
print(df_train.shape)
print(df_test.shape)

(891, 12)
(418, 11)

In [19]:
print(df_train.columns)
print(df_test.columns)

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')
Index(['PassengerId', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp', 'Parch',
       'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [2]:
# 程式區塊 B
train_Y = df_train['Survived']
ids = df_test['PassengerId']
df_train = df_train.drop(['PassengerId', 'Survived'] , axis=1)
df_test = df_test.drop(['PassengerId'] , axis=1)
df = pd.concat([df_train,df_test])
df.head()

,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [23]:
# 程式區塊 C
LEncoder = LabelEncoder()
MMEncoder = MinMaxScaler()
for c in df.columns:
    df[c] = df[c].fillna(-1)
    print(c)
    if df[c].dtype == 'object':
        print('object', c)
        df[c] = LEncoder.fit_transform(list(df[c].values))
    df[c] = MMEncoder.fit_transform(df[c].values.reshape(-1, 1))
df.head()

Pclass
Name
Sex
Age
SibSp
Parch
Ticket
Fare
Cabin
Embarked

,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1.0,0.118683,1.0,0.283951,0.125,0.0,0.775862,0.016072,0.000000,1.000000
1,0.0,0.218989,0.0,0.481481,0.125,0.0,0.879310,0.140813,0.575269,0.333333
2,1.0,0.400459,0.0,0.333333,0.000,0.0,0.984914,0.017387,0.000000,1.000000
3,0.0,0.323124,0.0,0.444444,0.125,0.0,0.070043,0.105390,0.381720,1.000000
4,1.0,0.016845,1.0,0.444444,0.000,0.0,0.699353,0.017630,0.000000,1.000000

In [11]:
train_X

,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1.0,0.118683,1.0,0.283951,0.125,0.000000,0.775862,0.016072,0.000000,1.000000
1,0.0,0.218989,0.0,0.481481,0.125,0.000000,0.879310,0.140813,0.575269,0.333333
2,1.0,0.400459,0.0,0.333333,0.000,0.000000,0.984914,0.017387,0.000000,1.000000
3,0.0,0.323124,0.0,0.444444,0.125,0.000000,0.070043,0.105390,0.381720,1.000000
4,1.0,0.016845,1.0,0.444444,0.000,0.000000,0.699353,0.017630,0.000000,1.000000
5,1.0,0.626340,1.0,0.000000,0.000,0.000000,0.401940,0.018425,0.000000,0.666667
6,0.0,0.587289,1.0,0.679012,0.000,0.000000,0.117457,0.102980,0.881720,1.000000
7,1.0,0.699847,1.0,0.037037,0.375,0.111111,0.582974,0.043004,0.000000,1.000000
8,1.0,0.463247,0.0,0.345679,0.000,0.222222,0.514009,0.023636,0.000000,1.000000
9,0.5,0.648545,0.0,0.185185,0.125,0.000000,0.187500,0.060528,0.000000,0.333333
10,1.0,0.816998,0.0,0.061728,0.125,0.111111,0.904095,0.034481,0.994624,1.000000
11,0.0,0.101838,0.0,0.728395,0.000,0.000000,0.053879,0.053669,0.338710,1.000000
12,1.0,0.819296,1.0,0.259259,0.000,0.000000,0.789871,0.017630,0.000000,1.000000
13,1.0,0.029096,1.0,0.493827,0.125,0.555556,0.494612,0.062874,0.000000,1.000000
14,1.0,0.934916,0.0,0.185185,0.000,0.000000,0.609914,0.017249,0.000000,1.000000
15,0.5,0.408116,0.0,0.691358,0.000,0.000000,0.219828,0.033117,0.000000,1.000000
16,1.0,0.761868,1.0,0.037037,0.500,0.111111,0.710129,0.058686,0.000000,0.666667
17,0.5,0.973201,1.0,0.000000,0.000,0.000000,0.216595,0.027273,0.000000,1.000000
18,1.0,0.931853,0.0,0.395062,0.125,0.000000,0.449353,0.037013,0.000000,1.000000
19,1.0,0.581930,0.0,0.000000,0.000,0.000000,0.261853,0.016023,0.000000,0.333333
20,0.5,0.323890,1.0,0.444444,0.000,0.000000,0.196121,0.052598,0.000000,1.000000
21,0.5,0.085758,1.0,0.432099,0.000,0.000000,0.218750,0.027273,0.774194,1.000000
22,1.0,0.595712,0.0,0.197531,0.000,0.000000,0.408405,0.017589,0.000000,0.666667
23,0.0,0.850689,1.0,0.358025,0.000,0.000000,0.058190,0.071104,0.096774,1.000000
24,1.0,0.702144,0.0,0.111111,0.375,0.111111,0.582974,0.043004,0.000000,1.000000
25,1.0,0.049005,0.0,0.481481,0.125,0.555556,0.489224,0.063093,0.000000,1.000000
26,1.0,0.284074,1.0,0.000000,0.000,0.000000,0.256466,0.016023,0.000000,0.333333
27,0.0,0.309342,1.0,0.246914,0.375,0.222222,0.132543,0.514290,0.435484,1.000000
28,1.0,0.677642,0.0,0.000000,0.000,0.000000,0.414871,0.017297,0.000000,0.666667
29,1.0,0.908116,1.0,0.000000,0.000,0.000000,0.537716,0.017330,0.000000,1.000000
...,...,...,...,...,...,...,...,...,...,...
861,0.5,0.336141,1.0,0.271605,0.125,0.000000,0.325431,0.024351,0.000000,1.000000
862,0.0,0.891271,0.0,0.604938,0.000,0.000000,0.120690,0.052460,0.655914,1.000000
863,1.0,0.804747,0.0,0.000000,1.000,0.222222,0.838362,0.137436,0.000000,1.000000
864,0.5,0.338438,1.0,0.308642,0.000,0.000000,0.165948,0.027273,0.000000,1.000000
865,0.5,0.135528,0.0,0.530864,0.000,0.000000,0.173491,0.027273,0.000000,1.000000
866,0.5,0.272588,0.0,0.345679,0.125,0.000000,0.929957,0.028945,0.000000,0.333333
867,0.0,0.775651,1.0,0.395062,0.000,0.000000,0.869612,0.100317,0.053763,1.000000
868,1.0,1.000000,1.0,0.000000,0.000,0.000000,0.461207,0.020455,0.000000,1.000000
869,1.0,0.459418,1.0,0.061728,0.125,0.111111,0.514009,0.023636,0.000000,1.000000
870,1.0,0.065850,1.0,0.333333,0.000,0.000000,0.572198,0.017330,0.000000,1.000000
871,0.0,0.084992,0.0,0.592593,0.125,0.111111,0.075431,0.104327,0.709677,1.000000
872,0.0,0.154671,1.0,0.419753,0.000,0.000000,0.741379,0.011688,0.247312,1.000000
873,1.0,0.928790,1.0,0.592593,0.000,0.000000,0.451509,0.019481,0.000000,1.000000
874,0.5,0.005360,0.0,0.358025,0.125,0.000000,0.850216,0.048702,0.000000,0.333333
875,1.0,0.642420,0.0,0.197531,0.000,0.000000,0.281250,0.016023,0.000000,0.333333
876,1.0,0.362940,1.0,0.259259,0.000,0.000000,0.744612,0.021128,0.000000,1.000000
877,1.0,0.734303,1.0,0.246914,0.000,0.000000,0.533405,0.017330,0.000000,1.000000
878,1.0,0.513017,1.0,0.000000,0.000,0.000000,0.538793,0.017330,0.000000,1.000000
879,0.0,0.746554,0.0,0.703704,0.000,0.111111,0.080819,0.163946,0.489247,0.333333
880,0.5,0.829250,0.0,0.320988,0.000,0.111111,0.158405,0.052598,0.000000,1.000000
881,1.0,0.579632,1.0,0.419753,0.000,0.000000,0.581897,0.017330,0.000000,1.000000
882,1.0,0.222052,0.0,0.283951,0.000,0.000000,0.751078,0.022435,0.000000,1.000000
883,0.5,0.067381,1.0,0.358025,0.000,0.000000,0.834052,0.022403,0.000000,1.000000
884,1.0,0.885911,1.0,0.320988,0.000,0.000000,0.960129,0.015682,0.000000,1.000000
885,1.0,0.763400,0.0,0.493827,0.000,0.555556,0.710129,0.058686,0.000000,0.666667
886,0.5,0.620980,1.0,0.345679,0.000,0.000000,0.140086,0.027273,0.000000,1.000000
887,0.0,0.355283,0.0,0.246914,0.000,0.000000,0.019397,0.060390,0.220430,1.000000
888,1.0,0.464778,0.0,0.000000,0.125,0.222222,0.994612,0.047630,0.000000,1.000000
889,0.0,0.086524,1.0,0.333333,0.000,0.000000,0.011853,0.060390,0.419355,0.333333
890,1.0,0.258806,1.0,0.407407,0.000,0.000000,0.691810,0.017046,0.000000,0.666667

In [4]:
# 程式區塊 D
train_num = train_Y.shape[0]
train_X = df[:train_num]
test_X = df[train_num:]

from sklearn.linear_model import LogisticRegression
estimator = LogisticRegression()
estimator.fit(train_X, train_Y)
pred = estimator.predict(test_X)

/Users/ianfan/anaconda3/envs/spinningup/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)

In [5]:
# 程式區塊 E
sub = pd.DataFrame({'PassengerId': ids, 'Survived': pred})
sub.to_csv('titanic_baseline.csv', index=False)